// src/app/layout.tsx
import type {Metadata} from "next";
import localFont from "next/font/local";
import {Collector} from "./Collector";



const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "dev test",
  description: "Generated by create next app",
};

export default function RootLayout({Collector}: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={${geistSans.variable} ${geistMono.variable}}>
        <Collector />
      </body>
    </html>
  );
}